description: "This is the website for the Digital Pasts Lab, introducing its various projects"
email: "digpasts@gmail.com"
twitter: "https://twitter.com/DigPastsLab"
twitter-handle: "@DigPastsLab"
webname: "Digital Pasts Lab"
BEn-tools: "https://babylonian.herokuapp.com/#/"